import time


print(' \t \t       -    \t \t')
print(' \t \t     /   \    \t \t')
time.sleep(0.5)
print(' \t \t    |  f  |  \t \t')
time.sleep(0.5)
print(' \t \t    |  u  |  \t \t')
time.sleep(0.5)
print(' \t            |  c  |           \t')
time.sleep(0.5)
print(' \t  ----  ----|  k  |---- ----  \t')
time.sleep(0.5)
print(' \t |     |    |     |    |    | \t')
time.sleep(0.5)
print(' \t |     |    |  y  |    |    | \t')
time.sleep(0.5)
print(' \t |     |    |  o  |    |    | \t')
time.sleep(0.5)
print(' \t |     |    |  u  |    |    | \t')
time.sleep(0.5)
print(' \t |                          | \t')
time.sleep(0.5)
print(' \t |                          | \t')
time.sleep(0.5)
print(' \t |                          | \t')
time.sleep(0.5)
print(' \t |                          | \t')
time.sleep(0.5)
print('---------                           ---------')
print("\n")
time.sleep(0.5)
print("\n")
time.sleep(0.5)
print("\t \t \t \t \t \t By: Rohit Narwal")
time.sleep(2)


